### ISSUE TITLE
[FR] Hide "min" extrema label independently from "max" label

### ISSUE THREAD

**Issue by m4sis** [kalkih/mini-graph-card#1016]
Bonjour,
Utilisant un graph pour ma production solaire je me retrouve avec le "min toujours a 0" vu que la nuit ca produits pas.
Je voudrais mettre a la plage la moyenne je joint la photo pour que ce sois comprehensible
![Sans titre2](https://github.com/kalkih/mini-graph-card/assets/75539603/0769038e-d96a-463a-8d83-5f02c0731a00)

![Sans titre](https://github.com/kalkih/mini-graph-card/assets/75539603/a67810bf-552a-4ba3-88e4-7af5e97912fd)

**Comment by ildar170975** [comment]
1. Please write in English - then more people will understand you.

2. This issue is a QUESTION. Suggest to ask similar questions in the dedicated Community thread (https://community.home-assistant.io/t/lovelace-mini-graph-card/71385), probably you will get answers faster & share your experience with other people. Leave GitHub for reporting bugs & proposing feature requests (FR).

3. If you need to hide a "min" label - use card-mod:
```
        type: custom:mini-graph-card
        entities:
          - sensor.xiaomi_cg_1_temperature
        show:
          labels: true
          average: true
          extrema: true
        style: |
          .info.flex div.info__item:nth-child(1) {
            display: none;
          }
          .info.flex div.info__item:nth-child(2) {
            text-align: left;
          }
```
So far this is the only possible solution (w/o changing a mini-graph-card's code).
More examples for using card-mod for mini-graph-card are presented here: https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/1396, scroll down for "mini-graph-card" section.

4. Currently an `extrema` option is used to show/hide both "min" & "max" labels. If you wish to propose to manage them independently - consider creating a separate FR with a detailed description of your proposal.

**Comment by m4sis** [comment]
Thanks, that's exactly what I wanted.

Otherwise, how do we reduce the spacing between lines?

**Comment by ildar170975** [comment]
> Otherwise, how do we reduce the spacing between lines?

Sorry, how is that related to the main issue?
Suggest to ask similar questions in a dedicated Commumity thread.

**Comment by m4sis** [comment]
ok I will open a new thread for my question which has nothing to do thank you

**Comment by ildar170975** [comment]
Hmm, you proposed a FR - and then closed it.
