### ISSUE TITLE
Using same tile with 2 graphs but different max/min

### ISSUE THREAD

**Issue by ghiki** [kalkih/mini-graph-card#1053]
Is it possible, in the same tile, get the info from two sensors using the sensor's recorded max/min as top high/low for the graph?

I mean, now I have this:

![imagen](https://github.com/kalkih/mini-graph-card/assets/854302/5071ef1c-b1ba-4b55-ba6b-d899167dc177)

And I want something like these two graphs:

![imagen](https://github.com/kalkih/mini-graph-card/assets/854302/ad3aeaf0-81d6-47a4-97ed-d64ea753141d)

One over another.

I think this worked on the past, but now, it makes combined graph like in the 1st, with lack of detail

**Comment by ghiki** [comment]
I think this is related with
https://github.com/kalkih/mini-graph-card/discussions/1049

**Comment by ildar170975** [comment]
1. This is a "card",  not a "tile". To avoid confusing with a standard Tile card.
2. The https://github.com/kalkih/mini-graph-card/discussions/1049 is about defining different bounds (`lower_bound`, `upper_bound`) per-entity - which is meaningless since these options are defined per-Y-axis.
3. The 1st card is wrongly contains two sensors with different UoMs on the same Y-axis. In this part it is same user mistake as in https://github.com/kalkih/mini-graph-card/discussions/1049.

**Comment by ildar170975** [comment]
Explanations provided, closed.
