### ISSUE TITLE
Feature Request: Fill thresholds (horizontal-banded gradient)

### ISSUE THREAD

**Issue by raffertyp1** [kalkih/mini-graph-card#112]
I saw that you had previously experimented with applying gradients to the fill, but ultimately decided against it (your post: https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/184). 

In that setup, the gradient changes were displayed as _vertical_ bands (matched to x-axis values), which is why it may look a bit strange. 

![0c0329971b881b930e380f45c6f192080617b4ad](https://user-images.githubusercontent.com/24816539/60436211-93b79000-9bd9-11e9-9b24-caa2885ed112.png)

I'd like to request _horizontal_ bands (matched to y-axis values) that mimics the line color thresholds. See the example below.

![Chart-Gradient](https://user-images.githubusercontent.com/24816539/60436095-5521d580-9bd9-11e9-88d4-0db6497b4d46.jpg)

If I was giving my full wishlist, I'd ask for an option to hide the line and only show the fill, but I'll open a separate issue for that :)

**Comment by raffertyp1** [comment]
As another example, here is a codepen that I forked with a simpler color scheme:
https://codepen.io/anon/pen/jjzWJq

**Comment by kalkih** [comment]
Yeah, I experimented with that prior to the rework of color thresholds (thresholds are now rendered along the Y-axis, instead of the x-axis).

Could give it another shot now when the thresholds are rendered differently, should work/look better.
Might be problematic when combined with the `fill: fade` option, can't guarantee it will work when used with that option.

Feel free to open another issue for the "hide line" request 👍

**Comment by kalkih** [comment]
This is now available in the latest release 🎉
