### ISSUE TITLE
line_color and color_treshold aren't entity specific?

### ISSUE THREAD

**Issue by Nickduino** [kalkih/mini-graph-card#1148]
This might be me but I don't get why this doesn't work:

![image](https://github.com/user-attachments/assets/7ca9b873-89bd-4dbb-8d12-6eb5d034eec2)

While this does :

![image](https://github.com/user-attachments/assets/0715b394-fc0c-41d5-9ec5-4469043de4c6)

What if I wanted dynamic colors for both lines (but with different thresholds)? How could I do that?

**Comment by ildar170975** [comment]
Color thresholds is a global option.
There is a PR for making thresholds per entity: https://github.com/kalkih/mini-graph-card/issues/153

**Comment by Nickduino** [comment]
> There is a PR for making thresholds per entity: #153

Ok. But that was a secondary question.

Can you tell me why my first example didn't work while the second did (so, one dynamic line and one light blue line) with nearly the same code?

**Comment by ildar170975** [comment]
“line_color” is a global option. It is mainly supposed to be used for a single-entity card. Otherwise it is supposed to be defined as a list - for many-entities card. 
For static colors, it is advised to use a “color” option per-entity. If defined - it overrides “color_thresholds”. 

Based on said:
1. The 1st card contains wrong code - misplaced “line_color” and misplaced “color_thresholds”. Default colors are used. 
2. The 2nd card contains “color” for the 1st entity and a global “color_thresholds”: so the 2nd entity uses a dynamic color, the 1st entity uses a static defined color.

**Comment by Nickduino** [comment]
Thank you!
