### ISSUE TITLE
Whether cumulative display is supported?

### ISSUE THREAD

**Issue by tinyhugh** [kalkih/mini-graph-card#1188]
unused memory + used memory
![image](https://github.com/user-attachments/assets/7c327bc0-40d6-4f7c-a350-178464b69425)

**Comment by ildar170975** [comment]
1. If you closed this Discussion because you found an answer - then you should have posted the answer. These Discussions are not only for you, they are for other people as well.
2. Suggest to ask questions about "how to..." in the [main Community thread.](https://community.home-assistant.io/t/lovelace-mini-graph-card/71385), Discussions are mainly for other purpose.

**Comment by tinyhugh** [comment]
No relevant solution has been found yet
