### ISSUE TITLE
Cache computed values

### ISSUE THREAD

**Issue by maxwroc** [kalkih/mini-graph-card#173]
Even with current cache the rendering of the graph looks little bit slow-ish. We could try to improve it by caching calculated/aggregated points. 

Pros:
* reduced loading time
* smaller amount of data stored in IndexedDB

Cons:
* no ability to share cache with other graphs (though it is not a common case and it is actually broken now anyway #171 )

I think it is an option worth to consider or at least testing.

**Comment by kalkih** [comment]
Smart, great idea!

I've not really noticed that the initial calculations are slow when all data is already cached, but might have too simple graphs / strong computer 😄.
As soon as history API calls is required it's definitely slow, but that's another issue.

From the top of my head, we actually don't use the raw history data for much, except for graph calculations and the extrema (max, min, average) I think, so this should be doable.

I've noticed overall browser performance can get pretty bad when there's a couple of hundred/thousand data points in a graph, haven't really looked into it, so not sure if this is caused by the graph calculations or by the actual rendering of the SVG.

**Comment by tiszavolgyi** [comment]
This would be awesome. I had to turn off the graph because my sensors generate too much data (2-3 data point in every second) and when I open a screen where the graph was, the host CPU run at 100% for a minute or so (not a Pi, but a decent Virtual Machine) . The cards are generated very slowly. I tried updating to version 0.9.0 and turn on cache, but the issue remained. I will try to modify my sensor to send less data and turn back on later, but this caching solution would be great.
