### ISSUE TITLE
[Feature request] Have label/name overlap with graph

### ISSUE THREAD

**Issue by hajo62** [kalkih/mini-graph-card#176]
Feature Request:
For graphs with some seldom peaks it might be a nice feature to let those use the full widget height, even when drawing though the text elements. One would see more details of the graph.

![image](https://user-images.githubusercontent.com/15800980/67156855-2c5a5300-f324-11e9-8c54-98501eda2156.png)
instead of
![image](https://user-images.githubusercontent.com/15800980/67156857-3a0fd880-f324-11e9-9fa2-955646398bba.png)

**Comment by kalkih** [comment]
I like the idea, thanks.

**Comment by sgvj** [comment]
Yes please. Would be such a visual improvement.

**Comment by cburkins** [comment]
New to Home Assistant, and loving mini-graph-card.   I think this would be a neat feature

**Comment by MaxVRAM** [comment]
I'm trying to start digging into JS and wouldn't mind helping out if I can. @kalkih I haven't looked to heavily into the code, but any clues on where to start looking and what any major roadblocks might be in getting it implemented, off the top of your head?

**Comment by kalkih** [comment]
The tricky part here is probably mostly to get the layout working properly I think.
I guess we would have two ways of going about the layout, either by positioning the graph element `absolute` and have the rest of the content positioned `relative`, or the other way around, have the graph element `relative` and the rest of the content `absolute`.

The relative positioned content would be the deciding factor for the height of the card and the other content would basically be "floating" (`position: absolute`) on top or beneath the relative positioned content.

I would probably try the first suggestion, having the graph positioned absolute. What we would have to do then is to make sure the graph is rendered at the height of the card. And since the height of the card is based on the height of all of it's relative positioned content, the height is dynamic, so would be a good use-case for Javascript to figure out the total card height.

**Comment by MaxVRAM** [comment]
@kalkih - I'll start poking around in my spare time. Cheers for the info!

**Comment by hajo62** [comment]
I see you are thinkig about a solution. Thanks for that.
You want to have in mind, that you could parametrise that i.e. bottom, half full or percentage of card height.
