### ISSUE TITLE
NaN on actual value but not on historical

### ISSUE THREAD

**Issue by D3nnisd** [kalkih/mini-graph-card#177]
When i add a system monitor sensor  it shows the line, but the number stays "NaN". If i move my cursor to a dot on the line, it does show the number.
Value with no cursor:
https://i.imgur.com/JY8CUiB.png
Value when pointing on a line:
https://i.imgur.com/nTsVC5J.png

**Comment by kalkih** [comment]
Hey,
Most likely reason: Your sensor is not reporting its state as a proper number and instead as a string. e.g. it's comma separated instead of dot separated (0,22 instead of 0.22).

Could also be if there's no state available at the time.

You can check the state by navigating to `http://[YOUR-HA]:[IP]/developer-tools/state` and selecting the entity in the dropdown.

**Comment by D3nnisd** [comment]
Hey!

Thanks for the reply. It indeed does report as 0,22 instead of 0.22. How do i fix that?

thanks!

**Comment by kalkih** [comment]
You could create a template sensor of the sensor and parse the string and then use that sensor in the graph, but that's quite annoying.

I think this should be addressed directly in the card since I could see this being a pretty common issue.
Will release a new version later today with a fix included.

Thanks!

**Comment by kalkih** [comment]
Latest version should now be able to handle these type of states.
