### ISSUE TITLE
Mini graph and history are showing different values

### ISSUE THREAD

**Issue by hajo62** [kalkih/mini-graph-card#192]
Today I recognized that the **mini graph** and the **history** are showing different values:
<img width="300" alt="minigraph" src="https://user-images.githubusercontent.com/15800980/67632051-71d7cc80-f89e-11e9-9377-15ed0d63d071.png">
<img width="300" alt="history" src="https://user-images.githubusercontent.com/15800980/67632052-72706300-f89e-11e9-9c89-ec699a786b13.png">

To see details of the values, I show 12 points_per_hour.

**Comment by kalkih** [comment]
Could you try changing hours_to_show to something else then refresh the page -> change back hours_to_show -> refresh the page.

That will clear any cached values.
Is it still wrong?

Did that solve it?

**Comment by hajo62** [comment]
I thought, I had done this before, but maybe without saving the changes and just looking at the graph in the "edit" view.
I tried again and now the graphs (two showed the problem) are looking correct.

**Comment by kalkih** [comment]
Okay, great!
I think there's a bug in the code though.

When there's no history data available for a data point in the graph, we'll use the last known calculated data point to fill this data.
Each calculated data point could be based of on multiple history entries and is by default calculated by the average of those history entries.
So instead of using the last known **calculated data point** for missing data points as we do right now, we should use the actual last known **raw history entry**.

I don't know if this make sense to you but I'm fairly confident this is the cause.

Thanks for letting me know about this issue, should be fairly easy to fix I think.
