### ISSUE TITLE
Dynamic Line Color not working as expected

### ISSUE THREAD

**Issue by dodo1337** [kalkih/mini-graph-card#227]
Hey,
today I noticed that somehow the coloring is not working as expected when dynamic line colors are in use.
There is a Hugh difference in the colors between several states of the card (hover, hover graph line, no hover).

View with no hover
![View no Hover](https://user-images.githubusercontent.com/35460627/71717955-0bc97180-2e1a-11ea-817c-b76f722395ce.png)

Hover the graph line
![Hover Graph Line](https://user-images.githubusercontent.com/35460627/71717954-0b30db00-2e1a-11ea-9497-a05befbede8c.png)

Hover the card
![Hover Card](https://user-images.githubusercontent.com/35460627/71717951-0b30db00-2e1a-11ea-9d70-c8d1de862875.png)

Card Config
![Config](https://user-images.githubusercontent.com/35460627/71717950-0b30db00-2e1a-11ea-87c9-7d97b7a81be6.png)

How can I help?
Best
  Dominik

**Comment by kalkih** [comment]
Hello,
This is expected behaviour, I'll try to clarify what you're seeing and why you're seeing it.

Basically I found it to be too demanding to calculate and interpolate the exact gradient color for each point, the points (this is what you see when hovering) will therefore only display in static colors, the ones specified in the configuration. The line does however by default have an effect where the threshold colors gradually transition into each other, this is the effect you're seeing, the line and the points do not match since their colors are calculated differently.

So in your case for example, all points below zero will display as `#3333ff`(blue), while the line will gradually transition between blue at `-2` to green at `0`, values close to `0` would be more blue than green and vice versa.

If you find this annoying, you can disable the smooth line color transition by setting the option `color_thresholds_transition` to `hard`, which should make the colors of the line and points match better but you'll lose the smooth color transitions.

**Comment by kalkih** [comment]
We should maybe not render the points in color threshold colors at all and instead in font color or something to cause less confusion, but not sure.
The whole hover over points solution does not work well at all in detailed graphs regardless of color, as in your example, it just gets too cluttered.

**Comment by dodo1337** [comment]
Thanks for the clarification. That was the option I obviously did not see in the docs.
The smooth transition is indeed much better from design / look&feel perspective. 
May the transition corridor just needs to be not so broad.

**Comment by kalkih** [comment]
There's a request open for a "transition rate" scale #118
