### ISSUE TITLE
Import of { LitElement, html, svg} not working anymore: "Card not found" error in Home Assistant

### ISSUE THREAD

**Issue by MarsWarrior** [kalkih/mini-graph-card#24]
This line:
```
import { LitElement, html, svg } from 'https://unpkg.com/@polymer/lit-element@^0.6.2/lit-element.js?module';
```
Does not work anymore. If I remove the "^", the card works again in Home Assistant.
I also noticed that version 0.6.5 also seems to work with your card.

**Comment by kalkih** [comment]
Hello,
Since version 0.0.8 this card is no longer relying this external loaded dependency.
With every [release](https://github.com/kalkih/mini-graph-card/releases), the source code and dependecies are compiled and bundled together and then made available as `mini-graph-card-bundle.js`.

The ability to use the source directly will be removed in the next update, I decided to continue support it for a few releases so that people had time to switch over to the bundle.

Check out the readme for up to date instructions.

**Comment by MarsWarrior** [comment]
I am using 0.08, but couldn’t get the bundle working so used the separate js files.

Will check if the latest bundle works for me and read the instructions.

**Comment by kalkih** [comment]
@MarsWarrior Did you get it working?

**Comment by MarsWarrior** [comment]
Yes! I got 0.1.0 working.

I had some troubles initially, but forgot to remove the old mini-graph resources 😄 

Will stick to the bundle from now on!
