### ISSUE TITLE
Request new aggregate function request timedavg

### ISSUE THREAD

**Issue by i00** [kalkih/mini-graph-card#260]
The average function returns the average of readings within the given period...

It would be great if it could also average over the time period .. for e.g:
If I have items grouped by hour and I have readings of:
0:00 - 5
0:45 - 10
The ave will display a reading of 7.5 - as there were two readings within the period... however the first reading was for 45 mins where as the second reading was for 15 ... it would be great if there was an average to weight the data based on times.
i.e.:
v=value
t=time
p=total time in period
((v1 * t1) + (v2 * t2) + ...) / p

((5 * 45) + (10 * 15)) / 60 = 6.25

Thanks

**Comment by Mikk36** [comment]
I agree, this is also an issue where I try to graph a fan being active, because whereas a temperature might have many many points regularly, an "active or not" sensor is likely to be optimized away by HA.
![Annotation 2020-02-13 100422](https://user-images.githubusercontent.com/5886412/74413615-6b1e9680-4e48-11ea-89e9-b4499a809a7b.jpg)
![Annotation 2020-02-13 100445](https://user-images.githubusercontent.com/5886412/74413618-6ce85a00-4e48-11ea-9c77-687fe0288d11.jpg)
As you can see, it shows 25% for both 01:01-02:00 and 02:01-03:00, but the fan was only active for 5 minutes, from 01:27 to 01:32.
