### ISSUE TITLE
Shorter duration possible?

### ISSUE THREAD

**Issue by craigueh** [kalkih/mini-graph-card#273]
Would it be possible to have an option for a shorter duration like 1min,5min etc?

I use this card for "real-time" internet traffic usage and it's not really any use only being able to see traffic over the past hour as the resolution in data points is just not there.

For example, if I compare the graph to the Hass History graph most of the peaks are missing. I did a speed test on my fibre line and the history graph shows a jump to 966mbps for about 30s but the mini-graph-card component never even registered the jump.

If we could have a shorter windows of say 1min then the card would hopefully display more accurate real-time stats.

**Comment by kalkih** [comment]
Values below `1` is actually supported, it did however not work very well in previous versions of the card, hence why it's not documented as supported.
Some of the issues might have been fixed with the altest release of the card.

This should give you a graph with one hour of data and a data point for every minute.
```yaml
hours_to_show: 1
points_per_hour: 0.016666666666667
```

GIve it a shot!
