### ISSUE TITLE
Use theme color definitions if color_thresholds_transition is set to hard

### ISSUE THREAD

**Issue by Phontana** [kalkih/mini-graph-card#280]
Is it possible to only calculate the graph colors if the `color_thresholds_transition` is set to `smooth`? So we can use theme variables if this option is set to `hard`? This would make the styling of the frontend easier by defining all graph colors in variables.

This was mentioned before in https://github.com/kalkih/mini-graph-card/issues/236.

**Comment by kalkih** [comment]
Should keep #118 in mind when implementing.

**Comment by Phontana** [comment]
I solved my issue by using decluttering-card, so this is not needed anymore.

**Comment by bojanpotocnik** [comment]
Could you please reopen this issue, because the behaviour mentioned in [this issue comment](https://github.com/kalkih/mini-graph-card/issues/236#issuecomment-588133943) still kinda defies the point of dynamic line colour (dots are only shown when you select the line, so on some view-only dashboard the line is single color).
