### ISSUE TITLE
Smoothing false not helping

### ISSUE THREAD

**Issue by IanAdd** [kalkih/mini-graph-card#388]
It I use the standard ha graph then I can get squared off value changes.
Here I can't find how, smoothing: false just changes smoothness to triangles. 
Am I missing a setting?

**Comment by kalkih** [comment]
This card doesn't behave like the default graph card, it's based on time interval (points_per_hour) & the moving average (or the aggregate functions set in the config) of that interval.

Smoothing just disables the interpolation between each two data points which otherwise result in the smooth/curved line effect.

To get the effect you want you would have to increase the resolution of the graph (the `points_per_hour` option).
