### ISSUE TITLE
Feature Request: Icon in legend

### ISSUE THREAD

**Issue by emouawad** [kalkih/mini-graph-card#401]
Would it be possible to add for the entities, in the legend, an icon (mdi icon set)
That way  we could - possibly - not add the name where some entities can be recognized easily by _an icon only_.

Currently if we ommit the name the friendly_name is naturally being filled automatically - that's not always pretty for graphs with lots of entities in the legend - icons might be better suited here.

**Comment by rdlaner** [comment]
+1 for this. I have a temperature graph that graphs multiple entities using a color threshold. Since the graph uses a color threshold, the legend will show the same color for all entities if they are in the same color threshold making it hard to know which line of the graph is very which entity.

Ideally, if each line graph got its icon that was reflected in the legend (eg circle, triangle, square, etc.), then each line could be identified w/o relying on color.
