### ISSUE TITLE
Hide time period when there are no updates.

### ISSUE THREAD

**Issue by agneevX** [kalkih/mini-graph-card#412]
Hello,

Can you add an option to hide the period when there are no updates so it appears as one continuous flow even though there were no updates?

Thanks.

**Comment by kalkih** [comment]
Would need to rewrite the entire graph generation for this since it's written in a way that's based on the moving average & even time intervals.
I guess you could fake it by just hiding the points afterwards if they are equal, I don't see me implementing this though but feel free to submit a PR if you think this would add value.
