### ISSUE TITLE
Graphs shows with bugs on Lenovo Tab

### ISSUE THREAD

**Issue by RestOp** [kalkih/mini-graph-card#422]
Hello,

i have problem with graphs, they looks so
![image](https://user-images.githubusercontent.com/46259141/90547349-ac8f5600-e18b-11ea-9860-5167a0b2032d.png)

Have to be so
![image](https://user-images.githubusercontent.com/46259141/90547386-bb760880-e18b-11ea-89a5-f6895d2c8880.png)

I have this problem on my Lenovo 10 Pro Tab with Android 7.1.1.
I checked in Home Assistant APP, in Chrome and in Opera. Behavior is the same.
I tryed zoom the window in Chrome and the problems becomes better, but goes not away.

My config is 
`
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Temperature
                points_per_hour: 2.0
                entities:
                  - sensor.th_livingroom_temperature
                line_color: var(--accent-color)
                line_width: 5
                font_size: 80  
                show:
                  labels: false
                color_thresholds:
                  - value: 26
                    color: "#f39c12"
                  - value: 27
                    color: "#d35400"
                  - value: 28
                    color: "#e74c3c"
              - type: custom:mini-graph-card
                entities:
                  - sensor.th_livingroom_humidity
                line_color: blue
                name: Humidity
                points_per_hour: 2.0
                line_width: 5
                font_size: 80
                show:
                  labels: false  
`

but the simple
`         
      - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.th_livingroom_temperature
              - type: custom:mini-graph-card
                entities:
                  - sensor.th_livingroom_temperature
              - type: custom:mini-graph-card
                entities:
                  - sensor.th_livingroom_temperature`
do not work also

Please fix if it possible.

PS
If i understood right, the problem occures if i have more then 2 graphs on page.

Update.
I got also probems with 2 Graphs

Thanks a lot!

**Comment by wdmnn** [comment]
I indeed have the same issue and already reported it here:
https://github.com/kalkih/mini-graph-card/issues/352#issuecomment-655982274

Although I have to say I'm not sure if it's related to the Lenovo Tab I'm using but your issue at least sounds familiar to me

**Comment by RestOp** [comment]
In all cases will be good if it will  be sovled

**Comment by RestOp** [comment]
It seems that i have found a way to get it work.
For me helped to set
              **- filter: opacity(100%)**  in styles of card on the card before the graph card.
![image](https://user-images.githubusercontent.com/46259141/92287681-bbeffc80-ef0a-11ea-8d64-474b90b977b4.png)

Please try it also.

**Comment by Strixx76** [comment]
Same problem here. Done a lot of research this morning, trying to find a pattern helping you to solve this issue. Here is what I have found so far.

Bur first of all: There is only an issue when the graphs are filled. By setting “fill: false” the issue goes away!

I have now tested with the following four different tablets:
Huawei MediaPad T5 (Android 8.0, screen res.: 1920x1200)
Lenovo Tab M10 plus, TB-X704L (Android 7.1.1, screen res.: 1920x1200)
Lenovo Tab 3 Plus, YT-X703F (Android 7.1.1, screen res.: 2560x1600)
Lenovo Tab 2, A10-70F (Android 6.0, screen res.:1920x1200)

Problem with graphs not rendering or rendering badly never occurs on my desktop using Chrome or Edge. Neither is there a problem with the Huawei MediaPad tablet. I have also tested on my phone, Huawei P9, without any issues.

I have three test views in Home Assistant.
1)	4 pcs Dynamic line color mini-graph-cards stacked vertical
2)	1 pcs Multiple entities card
3)	2 pcs Dynamic line color mini-graph-cards NOT stacked, together with one entities card and one vertical stack with no mini-graph-cards.

On all three Lenovo tablets there is problems showing the graphs. On Tab M10 and Tab 3, you can sometimes see one or two, out of four, graphs, the other ones is just a big colored field, like the picture above.

On the Tab 2 there is nothing displayed, except text. Once out of ten times (app.) one graph is showing like it should. And if rotate the screen back and forward a couple of times, the app crashes when displaying the test view.
The problem is only with test view 1 and 2, and never with test view 3.

Could it be that the problem is when rendering more than one graph inside an element that causes this issue?
But why is it only on the Lenovo tablets this problem shows, and on all three?

Pleas let me know if I can test something else to help you solve this issue!

**Comment by IDmedia** [comment]
I've fixed the issue on my tablet. The problem is that Android Webview is outdated. On another tablet I have I had to uninstall Chrome in order to make it work in the Kiosk app I use.

Download/update from here: https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en&gl=US

You may have to optin for beta-versions on some devices. If the problem persists just disable/uninstall any other browser you don't use or try to update them as well/opt in for beta.

**Comment by RomRider** [comment]
This is definitely related to old Android versions and outdated webview version (for all the apps but Chrome)/chrome versions. If you can, update webview/chrome or move to webview beta/chrome beta.
If you opt in for webview beta, you'll also have to change your default webview in the developers options on your Android device like so:
![Screenshot_20210120-004406.jpg](https://user-images.githubusercontent.com/21064206/105107653-d4774280-5ab8-11eb-8da2-3a019142caa5.jpg)

Unfortunately, there's not much we can do here.

**Comment by Strixx76** [comment]
Yes. For sure it is due to "bug" in Android WebView. The issue has disappeared for me since a couple of weeks ago. Must probably when I received an update.
