### ISSUE TITLE
NaN with binary_sensor after database issue

### ISSUE THREAD

**Issue by michaelblight** [kalkih/mini-graph-card#437]
I had a power outage and afterwards HA wouldn't start, so I first restored from a snapshot (which didn't help) and then deleted the database (which did help). However, since doing so, the existing `binary_sensors` no longer work with `mini-graph-card`.

In the Developer Tools they show as on/off as expected, but in the card they show as NaN.

I have tried the following:
- cleared the cache
- removed and reinstalled `mini-graph-card` (using HACS)
- checked I don't have any other `mini-graph-card` files lurking about
- tried multiple binary sensors, some currently on and others off.

Chrome's developer tools show the response from HA for the state history looks normal
```
[[{"attributes": {"device_class": "motion", "friendly_name": "Andrew", "on": true, "temperature": 28.0}, "entity_id": "binary_sensor.andrew", "last_changed": "2020-09-01T07:14:03.928000+00:00", "last_updated": "2020-09-01T07:14:03.928000+00:00", "state": "off"}]]
```

Do you have any thoughts about what is going on?

**Comment by kalkih** [comment]
The `state_map` option has some issues with caching, I don't exactly remember what it was but sounds like it could be what's causing this.
Try opening HA in an incognito tab and see if the issue is gone. If so, you can manually go into the browsers dev-tools -> application -> storage -> indexedDB and delete the cache. Or just disable cache in the card configs `cache: false`

**Comment by michaelblight** [comment]
Yeah that worked. I took a more ballistic approach to clearing the cache and the issue seems to be gone now. Thanks.
