### ISSUE TITLE
Add option for bar charts to always draw bars from 0.

### ISSUE THREAD

**Issue by jsiemek** [kalkih/mini-graph-card#455]
I really love mini-graph-card! It gives us a lot's of display possibilities.

One small thing: 
I use HA to manage terrariums my daughter is breeding lizards.
Beside  temperature and humidity we record all worms given to them.
Bar chart from mini-graph-card shows how man has been given to them.
Unfortunately if pattern is  like 5,5,5,4 its show the way it looks like 5,5,5,0 because
it's draw from x-axis at 4. It's misleading a bit, especially because I use old phones as management panels, so everything is small.

Could you please add option to draw bar charts from 0?

**Comment by trankillity** [comment]
I would also like to request this feature, but for a different reason - negative values.

Currently the graph scales based on the lowest value, which means that negative values are shown in positive Y axis. This is obviously undesirable.

My use case is a ROI graph for my solar generation based on tariffs vs usage. Some cloudy days are negative ROI, so would like to see that illustrated.

**Comment by jsiemek** [comment]
@trankillity 
it's already there, check: **lower_bound** option.

**Comment by trankillity** [comment]
No, it's not. But I guess mine is technically a different request. What I want is the ability to show negative values as negative on the Y axis, rather than just scaling the Y axis to the range of values (as any normal bar chart should).

Example [here](https://peltiertech.com/wp-content/img200806/InvertChart03.png). Will make my own issue though.
