### ISSUE TITLE
chart completely missing if one of the entities doesn't exist

### ISSUE THREAD

**Issue by ktownsend-personal** [kalkih/mini-graph-card#487]
I had 3 mini-graph-card charts on my dashboard and they all completely disappeared when I disabled the yr integration. By disappeared, I mean it's as if they never existed. No placeholder unless I edit the dashboard, then I see the 3 "edit" footers without anything above them. Each chart had 3 entities, and the first entity no longer existed. I didn't test whether changing the order would make a difference before I created template entities to replace the missing yr entities. It would be better feedback in the UI if the chart would render the other entities correctly and give a visual indicator that the missing entity is missing.

**Comment by RomRider** [comment]
@kalkih, would it be ok to display a warning card instead of the graph if any of the entities defined in the `entities` array doesn't exist? Any smarter approach?
This is what is displayed in HA core for missing entities for eg:
![image](https://user-images.githubusercontent.com/21064206/104852297-70a71b00-58fa-11eb-8914-5272d36af473.png)

**Comment by kalkih** [comment]
Yes, sounds very reasonable to me!
