### ISSUE TITLE
No card type configured

### ISSUE THREAD

**Issue by jresende7** [kalkih/mini-graph-card#609]
Hello,

Need some help here...instaled via hacs, the url is on the resources page, but:

`No card type configured
- type: custom-mini-graph-card
  entities:
    - entity: sensor.speedtest_download
      name: Download
      color: green
    - entity: sensor.speedtest_upload
      name: Upload
      color: red
    - entity: sensor.speedtest_ping
      name: Ping
      color: yellow`

What am i missing here ?

**Comment by BangDroid** [comment]
Same issue here. Installed with hacs

I also tried `/community/mini-graph-card/mini-graph-card-bundle.js` because this is the directory structure on the file system.
But this gives 404 when accessing via browser. Only the default `/hacsfiles/mini-graph-card/mini-graph-card-bundle.js`  is accessible.
I've restarted home assistant, but I'm still getting No Card Type Configured.

**Comment by BangDroid** [comment]
Fixed my issue following this: https://community.home-assistant.io/t/solved-lovelace-conf-with-custom-cards-error-no-card-type-configured/183204/3

Removed the preceding hyphen and indentation.

**Comment by grigio** [comment]
+1 seems the path has changed
```
of chunk.625dfb042e2450e9da81.js:575 GET http://xx.xx.1.6:8123/hacsfiles/mini-graph-card/mini-graph-card-bundle.js net::ERR_ABORTED 404 (Not Found)
```

**Comment by grigio** [comment]
It's a problem with caching, you need to add the resource to `configuration.yml` and check the inspector
![Screenshot from 2021-05-29 13-29-40](https://user-images.githubusercontent.com/8074/120068671-3278ef80-c082-11eb-8cc5-c71835d51d6b.png)

**Comment by kalkih** [comment]
> No card type configured

Removing the initial dash before type should solve your issue `- type` -> `type`
