### ISSUE TITLE
Option to display the secondary state(s) on a new line

### ISSUE THREAD

**Issue by gfduszynski** [kalkih/mini-graph-card#656]
Hi, I'm working on my dashboard and would really like to show both humidity and temp state values when chart is very narrow.
![Screen Shot 2021-10-09 at 12 25 07](https://user-images.githubusercontent.com/1913102/136654497-195f21bf-97ae-4689-a3af-3582127ca995.png)

In the last row you can see what I mean, my goal would be to lower the font size and display one above the other.

Is this feasible ?

Thanks

**Comment by kalkih** [comment]
Hello, you got the `font_size` option to lower the size of the state.
You have the `show_state` option on an entity basis to display additional states.

**Comment by ildar170975** [comment]
May be achieved by card-mod, looks nice for 2 entities maximum :
https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/1956?u=ildar_gabdullin
![image](https://user-images.githubusercontent.com/71872483/150041921-bd51acb7-bd3e-4c8d-84f9-cfca54dab955.png)

**Comment by ildar170975** [comment]
Regarding the [provided mod](https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/1956?u=ildar_gabdullin):
Unfortunately, it is better to disable the “show points” option since the top state label is used not only for displaying the 1st entity’s state but also for displaying a value for the selected point of ANY graph.
Look at the picture: the bottom label contains a current state of the 2nd entity, the top label contains a state for the selected point of the same 2nd entity:
![image](https://user-images.githubusercontent.com/71872483/150059537-702cb6d2-5675-439d-bbd2-65d990e5028a.png)
So, this mod should be used w/o the “show points” option.
