### ISSUE TITLE
min/max value - use same datasets

### ISSUE THREAD

**Issue by Export33** [kalkih/mini-graph-card#68]
this card looks awesome. thank you.

i have an issue when showing min/max values.
labels, points and extrema should use the same dataset. otherwise the card shows different min/max values.
1. max value (highest selectable point) - 96,56
2. max value (label) - 96,92
3. max value (extrema) - 97,57

![maxvalues](https://user-images.githubusercontent.com/25232960/53698427-d3619d00-3ddc-11e9-9e89-9d049062fc6c.png)

or you could show the min/max value as a separate dot on the line. this would avoid the problem when the actual value is the highest one.

**Comment by kalkih** [comment]
That is the intended behavior

The graph + labels are based on a moving average, in order to achieve the smooth line curves.
The extrema is based on the actual max/min history entry (hence the name).

Not sure, I think it's useful to have the actual min/max and not just the moving average min/max, don't think I'll change this.

**Comment by Export33** [comment]
i also think that its useful to have the actual min/max.

what i dont like is the label min/max showing the min/max values of the moving average.
here is an actual example of my temperature graph. both actual temperature and max value are higher than the max value of the label.
while this is datawise correct it looks wrong for me when having just a quick glance at the card.
![temperature](https://user-images.githubusercontent.com/25232960/53700354-905df480-3df1-11e9-920d-991b3e9625b1.png)

on the other hand, when changing the behaviour, e.g a misplaced thermometer with 5 minutes direct sun a day would probably produce a high max value while still having a low average. this would would result in a wrong scaling.

i guess you shouldn´t change it and i´ll use the labels only to get less confused.

**Comment by kalkih** [comment]
> on the other hand, when changing the behaviour, e.g a misplaced thermometer with 5 minutes direct sun a day would probably produce a high max value while still having a low average. this would would result in a wrong scaling.

Yes, exactly, so changing the labels isn' really an option either.

> i guess you shouldn´t change it and i´ll use the labels only to get less confused.

Yes, I'll keep it as is 👍 

I think it makes more sense to keep the extrema as the actual min/max and not change it to the moving average extrema, because if that's what you're after you could more or less get it from looking at the graph labels.
