### ISSUE TITLE
Zero in Value is not Zero in Graph

### ISSUE THREAD

**Issue by Alex-joomla** [kalkih/mini-graph-card#800]
If I have a zero in the value which should be displayed, there is still a little bar as graph. Is it possible to show real nothing when the value is zero? 
![D0F11376-C648-4B7B-A3AE-B75AE57D419F](https://user-images.githubusercontent.com/32268233/173593858-ca072d9c-5d32-47dc-8401-86a11b940b15.jpeg)

**Comment by ildar170975** [comment]
What is displayed if some bar is selected?
Post a screenshot.

**Comment by Alex-joomla** [comment]
It shows zero:
![FD57A4F7-5B26-4A21-AA32-FB4CDE26F81A](https://user-images.githubusercontent.com/32268233/173608054-c3cb7ae7-5072-4ebe-b35e-95f3a5060be1.png)

**Comment by Alex-joomla** [comment]
And as far as I can see on your linked issue there is no real solution, is it?

**Comment by ildar170975** [comment]
What do you want?
Do you want to show these "zero" bars:
- as "shorter bars" (how short?);
- as "thin lines" (how thin?);
- as just missing bars?

[Here](https://github.com/kalkih/mini-graph-card/issues/714) a person asked for an option "do not show zero bars" - is it what you want?
If yes - I will close the current issue in the favour of [that issue ](https://github.com/kalkih/mini-graph-card/issues/714) (which was closed automatically since the person lost his interest).

**Comment by ildar170975** [comment]
> have zero bars

What is zero bars?
Just missing (not displayed) bars?

**Comment by Alex-joomla** [comment]
Of course!

**Comment by ildar170975** [comment]
Closing in favour of https://github.com/kalkih/mini-graph-card/issues/714

**Comment by ildar170975** [comment]
@Alex-joomla goto that old reopened issue and start monitoring it, also yo may write your thoughts regarding it.
