### ISSUE TITLE
[Feature request] show legend below graph

### ISSUE THREAD

**Issue by DSDV** [kalkih/mini-graph-card#818]
Hi all <3, 

if someone could add the option to move the legend (or other stuff like state etc) to other positions would be huge (: 

with kind regards

**Comment by ildar170975** [comment]
> to other positions

Please be more specific and list possible variants for each "staff".

**Comment by DSDV** [comment]
If we take the graph as fixed point there is left, right, under and on top of the graph. 
if i am not mistaken we have the state(s) and the legend as other parts of the mini-graph card.

So i guess depending on how much work it is to split them. moving them at once for example:
legend below graph or states left of graph. 

If it is possible i guess some would find splitting this per entity quite helpful. 
like showing one state per side of graph.

In general the option to specify the settings per entity is really cool (even though line thickness is missing) <3

i hope this explanation helps.

**Comment by ildar170975** [comment]
These explanations are too general.
Kind of "make everything cool".

Since this is a FR, please give more detailed algorithm.
Like:
a) For state - these variants:
- variant 1: description + picture
- variant 2: description + picture
- variant 3: description + picture

Otherwise everyone may imagine different ideas.
