### ISSUE TITLE
How can i reset or calibrate max min value in mini graph card.

### ISSUE THREAD

**Issue by maijo366** [kalkih/mini-graph-card#919]
I have wrong values in this card and in the history.
But i don´t want to clear the home assistant v2.db. Is there a way?

**Comment by ildar170975** [comment]
1. No way related to this card.
The card only gets data from DB.
Check solutions with using SQL, ask in the Community.

2. This issue is neither a bug nor a feature request.
It's a question.
Please ask similar questions in the dedicated mini-graph-card Community thread (https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/) and leave Github for bugs & FRs.
